### ISSUE TITLE
Error install with webpack

### ISSUE THREAD

**Issue by caiolima86** [flauc/angular2-easy-forms#1]
Hello,

I'm trying to install your library in my project based on: https://github.com/angular/angular2-seed

But I'm not getting, you know how I do to install the library with Webpack?

Thank you very much.

**Comment by flauc** [comment]
Hi @caiolima86  

I had a similar issue on another library. I don't really use webpack i prefer systemjs. However i tried to make the library work. Turns out it was quit strait forward. Easy-forms should work in exactly the same way. Here is the [link](https://github.com/flauc/angular2-notifications/issues/5). Let me know how it goes :+1:

**Comment by caiolima86** [comment]
Hello,

It worked perfectly, thank you for your help, I am newbie in the world of angular2.

Thank you for your attention =)

**Comment by flauc** [comment]
Don't mention it. I'm glad it worked out for you.

**Comment by vZanchiV** [comment]
You can add /components in your import

import { EasyFormsModule } from 'angular2-easy-forms/components';
