### ISSUE TITLE
Change the word 

### ISSUE THREAD

**Issue by lebsral** [flauc/angular2-easy-forms#5]
The word 'value' is confusing.  Under options the word value is used.  The a little further down the word is used again, but it is refering to the 'key' above.  Maybe change the 2nd one to 'defaultKey' ?

``` ts
new DropdownQuestion({
    key: 'isRecyclable',
    label: 'Is Recyclable?',
    options: [
      {key: '0',  value: 'No'},
      {key: '1',  value: 'Yes'}
    ],
    value: '1',
    order: 12
  }),
```

**Comment by flauc** [comment]
But it isn't really referring to the key above it only has the same value. I think the value makes a lot of sense here. Because the value in the options array refers to the value of the option and the value in the question refers to the current value. 

I went with the `value`˛key because of consistency (and a bit less code in the component), it's the same key i use in every question.
